import nconf from 'nconf'

nconf.argv().env({ separator: '_', lowerCase: true })

nconf.defaults({
  db: {
    host: 'postgres',
    database: 'avrs',
    username: 'root',
    password: 'password',
    dialect: 'postgres',
  },
  redis: {
    host: 'redis',
  },
  mailer: {
    service: 'yandex',
    auth: {
      user: 'devmailersender',
      pass: 'Pt23sdfaE_r',
    },
    from: 'devmailersender@yandex.ru',
  },
  auth: {
    secret: 'Dev secret string',
  },
  servicePlans: [
    {
      id: 'mbasis',
      type: 'month',
      name: 'Basis',
      time: 10,
      price: 25,
      period: 30,
      profitability: 20,
      profitabilityPerDay: 1,
      profitabilityPerHour: 0.1,
      profit: 5,
      amount: 30,
      memory: 1024,
      cpu: {
        from: 15,
        to: 19,
      },
    },
    {
      id: 'mstandard',
      type: 'month',
      name: 'Standard',
      time: 12,
      price: 50,
      period: 30,
      profitability: 20,
      profitabilityPerDay: 2,
      profitabilityPerHour: 0.17,
      profit: 10,
      amount: 60,
      memory: 2048,
      cpu: {
        from: 27,
        to: 32,
      },
    },
    {
      id: 'mpremium',
      type: 'month',
      name: 'Premium',
      time: 15,
      price: 150,
      period: 30,
      profitability: 20,
      profitabilityPerDay: 6,
      profitabilityPerHour: 0.4,
      profit: 30,
      amount: 180,
      memory: 3072,
      cpu: {
        from: 37,
        to: 42,
      },
    },
    {
      id: 'mbusiness',
      type: 'month',
      name: 'Business',
      time: 20,
      price: 250,
      period: 30,
      profitability: 20,
      profitabilityPerDay: 10,
      profitabilityPerHour: 0.5,
      profit: 50,
      amount: 300,
      memory: 4096,
      cpu: {
        from: 62,
        to: 79,
      },
    },
    {
      id: 'qbasis',
      type: 'quarter',
      name: 'Basis',
      time: 10,
      price: 75,
      period: 90,
      profitability: 25,
      profitabilityPerDay: 1.04,
      profitabilityPerHour: 0.104,
      profit: 18.75,
      amount: 93.75,
      memory: 1024,
      cpu: {
        from: 15,
        to: 19,
      },
    },
    {
      id: 'qstandard',
      type: 'quarter',
      name: 'Standard',
      time: 12,
      price: 150,
      period: 90,
      profitability: 25,
      profitabilityPerDay: 2.08,
      profitabilityPerHour: 0.17,
      profit: 37.5,
      amount: 187.50,
      memory: 2048,
      cpu: {
        from: 27,
        to: 32,
      },
    },
    {
      id: 'qpremium',
      type: 'quarter',
      name: 'Premium',
      time: 15,
      price: 450,
      period: 90,
      profitability: 30,
      profitabilityPerDay: 6.5,
      profitabilityPerHour: 0.43,
      profit: 135,
      amount: 585,
      memory: 3072,
      cpu: {
        from: 37,
        to: 42,
      },
    },
    {
      id: 'qbusiness',
      type: 'quarter',
      name: 'Business',
      time: 20,
      price: 750,
      period: 90,
      profitability: 30,
      profitabilityPerDay: 10.83,
      profitabilityPerHour: 0.54,
      profit: 225,
      amount: 975,
      memory: 4096,
      cpu: {
        from: 62,
        to: 79,
      },
    },
    {
      id: 'hbasis',
      type: 'half-year',
      name: 'Basis',
      time: 10,
      price: 150,
      period: 180,
      profitability: 40,
      profitabilityPerDay: 1.17,
      profitabilityPerHour: 0.117,
      profit: 60,
      amount: 210,
      memory: 1024,
      cpu: {
        from: 15,
        to: 19,
      },
    },
    {
      id: 'hstandard',
      type: 'half-year',
      name: 'Standard',
      time: 12,
      price: 300,
      period: 180,
      profitability: 40,
      profitabilityPerDay: 2.33,
      profitabilityPerHour: 0.19,
      profit: 120,
      amount: 420,
      memory: 2048,
      cpu: {
        from: 27,
        to: 32,
      },
    },
    {
      id: 'hpremium',
      type: 'half-year',
      name: 'Premium',
      time: 15,
      price: 900,
      period: 180,
      profitability: 50,
      profitabilityPerDay: 7.5,
      profitabilityPerHour: 0.5,
      profit: 450,
      amount: 1350,
      memory: 3072,
      cpu: {
        from: 37,
        to: 42,
      },
    },
    {
      id: 'hbusiness',
      type: 'half-year',
      name: 'Business',
      time: 20,
      price: 1500,
      period: 180,
      profitability: 60,
      profitabilityPerDay: 13.33,
      profitabilityPerHour: 0.67,
      profit: 900,
      amount: 2400,
      memory: 4096,
      cpu: {
        from: 62,
        to: 79,
      },
    },
    {
      id: 'ybasis',
      type: 'year',
      name: 'Basis',
      time: 10,
      price: 300,
      period: 365,
      profitability: 80,
      profitabilityPerDay: 1.48,
      profitabilityPerHour: 0.148,
      profit: 240,
      amount: 540,
      memory: 1024,
      cpu: {
        from: 15,
        to: 19,
      },
    },
    {
      id: 'ystandard',
      type: 'year',
      name: 'Standard',
      time: 12,
      price: 600,
      period: 365,
      profitability: 80,
      profitabilityPerDay: 2.96,
      profitabilityPerHour: 0.25,
      profit: 480,
      amount: 1080,
      memory: 2048,
      cpu: {
        from: 27,
        to: 32,
      },
    },
    {
      id: 'ypremium',
      type: 'year',
      name: 'Premium',
      time: 15,
      price: 1800,
      period: 365,
      profitability: 80,
      profitabilityPerDay: 8.88,
      profitabilityPerHour: 0.59,
      profit: 1440,
      amount: 3240,
      memory: 3072,
      cpu: {
        from: 37,
        to: 42,
      },
    },
    {
      id: 'ybusiness',
      type: 'year',
      name: 'Business',
      time: 20,
      price: 3000,
      period: 365,
      profitability: 80,
      profitabilityPerDay: 14.79,
      profitabilityPerHour: 0.74,
      profit: 2400,
      amount: 5400,
      memory: 4096,
      cpu: {
        from: 62,
        to: 79,
      },
    },
  ],
})

export default nconf
