import nconf from 'nconf'

nconf.argv().env({ separator: '_', lowerCase: true })

nconf.defaults({
  db: {
    host: 'postgres',
    database: 'avrs',
    username: 'root',
    password: 'password',
    dialect: 'postgres',
  },
  redis: {
    host: 'redis',
  },
  mailer: {
    service: 'yandex',
    auth: {
      user: 'devmailersender',
      pass: 'Pt23sdfaE_r',
    },
    from: 'devmailersender@yandex.ru',
  },
  auth: {
    secret: 'Dev secret string',
  },
  shop: {
    url: 'https://www.aversis-shop.com/',
    secret: '6959bfc3f2e47b86',
  },
  recaptcha: {
    siteKey: '6Lffyg8UAAAAAIt63I-Ezl3u9gud1Ht7AwmsC1-h',
    secretKey: '6Lffyg8UAAAAAMCwJFnQ14xeXRv0834EPYZUapwE',
  },
  servicePlans: [
    {
      type: 'basis',
      period: 30,
      time: 10,
      price: 25,
      profitabilityPerHour: 0.093,
      profitabilityPerDay: 0.93,
      amount: 28,
      memory: 1024,
      cpu: 5,
      productId: '5',
    },
    {
      type: 'basis',
      period: 90,
      time: 10,
      price: 75,
      profitabilityPerHour: 0.114,
      profitabilityPerDay: 1.14,
      amount: 102.75,
      memory: 1024,
      cpu: 5,
      productId: '6',
    },
    {
      type: 'basis',
      period: 180,
      time: 10,
      price: 250,
      profitabilityPerHour: 0.243,
      profitabilityPerDay: 2.43,
      amount: 437.5,
      memory: 1024,
      cpu: 5,
      productId: '7',
    },
    {
      type: 'basis',
      period: 365,
      time: 10,
      price: 500,
      profitabilityPerHour: 0.344,
      profitabilityPerDay: 3.44,
      amount: 1255,
      memory: 1024,
      cpu: 5,
      productId: '8',
    },
    {
      type: 'standart',
      period: 30,
      time: 12,
      price: 50,
      profitabilityPerHour: 0.156,
      profitabilityPerDay: 1.87,
      amount: 56,
      memory: 2048,
      cpu: 15,
      productId: '9',
    },
    {
      type: 'standart',
      period: 90,
      time: 12,
      price: 150,
      profitabilityPerHour: 0.19,
      profitabilityPerDay: 2.28,
      amount: 205.50,
      memory: 2048,
      cpu: 15,
      productId: '10',
    },
    {
      type: 'standart',
      period: 180,
      time: 12,
      price: 500,
      profitabilityPerHour: 0.41,
      profitabilityPerDay: 4.86,
      amount: 875,
      memory: 2048,
      cpu: 15,
      productId: '11',
    },
    {
      type: 'standart',
      period: 365,
      time: 12,
      price: 1500,
      profitabilityPerHour: 0.86,
      profitabilityPerDay: 10.32,
      amount: 3765,
      memory: 2048,
      cpu: 15,
      productId: '12',
    },
    {
      type: 'premium',
      period: 30,
      time: 15,
      price: 150,
      profitabilityPerHour: 0.373,
      profitabilityPerDay: 5.6,
      amount: 168,
      memory: 3072,
      cpu: 20,
      productId: '21',
    },
    {
      type: 'premium',
      period: 90,
      time: 15,
      price: 450,
      profitabilityPerHour: 0.46,
      profitabilityPerDay: 6.85,
      amount: 616.5,
      memory: 3072,
      cpu: 20,
      productId: '22',
    },
    {
      type: 'premium',
      period: 180,
      time: 15,
      price: 1000,
      profitabilityPerHour: 0.65,
      profitabilityPerDay: 9.72,
      amount: 1750,
      memory: 3072,
      cpu: 20,
      productId: '23',
    },
    {
      type: 'premium',
      period: 365,
      time: 15,
      price: 2000,
      profitabilityPerHour: 0.92,
      profitabilityPerDay: 13.75,
      amount: 5020,
      memory: 3072,
      cpu: 20,
      productId: '24',
    },
    {
      type: 'business',
      period: 30,
      time: 20,
      price: 250,
      profitabilityPerHour: 0.467,
      profitabilityPerDay: 9.33,
      amount: 280,
      memory: 4096,
      cpu: 40,
      productId: '25',
    },
    {
      type: 'business',
      period: 90,
      time: 20,
      price: 750,
      profitabilityPerHour: 0.57,
      profitabilityPerDay: 11.42,
      amount: 1027.5,
      memory: 4096,
      cpu: 40,
      productId: '26',
    },
    {
      type: 'business',
      period: 180,
      time: 20,
      price: 1500,
      profitabilityPerHour: 0.73,
      profitabilityPerDay: 14.58,
      amount: 2625,
      memory: 4096,
      cpu: 40,
      productId: '27',
    },
    {
      type: 'business',
      period: 365,
      time: 20,
      price: 3000,
      profitabilityPerHour: 1.03,
      profitabilityPerDay: 20.63,
      amount: 7530,
      memory: 4096,
      cpu: 40,
      productId: '28',
    },
  ],
})

export default nconf
